### ISSUE TITLE
Clarification on license

### ISSUE THREAD

**Issue by Cellesti** [BluebonnetField/slidge-style-parser#3]
Hello, i am trying to package Matridge for Alpine Linux, and this project is one of its dependencies.

I see your latest commit adds the AGPL-3.0 license file. However, Alpine requires that i list which variant of the AGPL-3.0 you are using.

The reason for this is Alpine uses SPDX identifiers, and SPDX has [deprecated](https://spdx.github.io/spdx-spec/v2.3/SPDX-license-list/#a3-deprecated-licenses) the AGPL-3.0 license identifier.

So, may i know if you are using `AGPL-3.0-or-later` or `AGPL-3.0-only`?

Thank you.

**Comment by BluebonnetField** [comment]
Hi Cellesti, thanks for asking. I think it makes sense to use the same license Slidge does. I couldn't find where that's specified, if you know what it is I can add it to the readme or wherever you need it.

**Comment by BluebonnetField** [comment]
Updated
