### ISSUE TITLE
Multiline code blocks in matrix drop newlines

### ISSUE THREAD

**Issue by truenicoco** [BluebonnetField/slidge-style-parser#4]
![Screenshot_20240728_223717](https://github.com/user-attachments/assets/0a5065b8-3025-4f3a-a17d-dd433180bec8)
![Screenshot_20240728_223812](https://github.com/user-attachments/assets/251c94ff-db5d-48d3-bda5-8413b4b11440)

**Comment by BluebonnetField** [comment]
Shoot, I'd fixed this for plain ``` code blocks but didn't test for ```language code blocks. Fixed

https://github.com/BluebonnetField/slidge-style-parser/commit/e65a593a121935a245ef02b24d2b9464665c05f8
