### ISSUE TITLE
Angle brackets should be escaped (XMPP→Matrix)

### ISSUE THREAD

**Issue by truenicoco** [BluebonnetField/slidge-style-parser#5]
Sending

> Hey, this \<will\> be stripped

from an XMPP client shows as:

> Hey, this be stripped

in Element. (and possibly other matrix clients)

**Comment by BluebonnetField** [comment]
Fixed in. Released to pypi
https://github.com/BluebonnetField/slidge-style-parser/commit/c88b701e961bdfb5aa4b8673c9d67475353f494d
